#!/usr/bin/env python3
"""Regenerate plugin and Marketplace imagery.

Outputs:
  - com.ewels.type-deck.sdPlugin/imgs/plugin/marketplace.png      (256×256)
  - com.ewels.type-deck.sdPlugin/imgs/plugin/marketplace@2x.png   (512×512)
  - com.ewels.type-deck.sdPlugin/imgs/plugin/category-icon.png    (28×28)
  - com.ewels.type-deck.sdPlugin/imgs/plugin/category-icon@2x.png (56×56)
  - docs/marketplace-app-icon.png                                 (288×288)
  - docs/marketplace-thumbnail.png                                (1920×960)
  - docs/marketplace-gallery-1.png                                (1920×960)
  - docs/marketplace-gallery-2.png                                (1920×960)
  - docs/marketplace-gallery-3.png                                (1920×960)

The plugin manifest icons (`imgs/plugin/marketplace*.png`,
`imgs/plugin/category-icon*.png`) are tracked because the plugin needs them at
runtime. Everything in `docs/marketplace-*.png` is gitignored — those are for
one-off Marketplace upload only and can be regenerated by re-running this
script.

Requires `fontTools`, `rsvg-convert`, and ImageMagick (`magick`/`convert`).
The "Type Deck" wordmark is flattened to vector paths from SF Pro Bold for
deterministic typography.
"""

import subprocess
from pathlib import Path

from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont

REPO = Path(__file__).resolve().parent.parent
DOCS = REPO / "docs"
PLUGIN_IMGS = REPO / "com.ewels.type-deck.sdPlugin/imgs/plugin"
SF_FONT = "/System/Library/Fonts/SFNS.ttf"

# Brand palette — dark backdrop for Marketplace's dark UI.
BG = "#0d1117"
FG = "#f0f6fc"
MUTED = "#9ca3af"
ACCENT = "#a78bfa"

# Reused icon paths (the same artwork shipped to the Stream Deck action icons).
QUOTE_PATH = "M6 17h3l2-4V7H5v6h3zm8 0h3l2-4V7h-6v6h3z"
CYCLE_PATH = "m0 9l7 4v-3h9V3l-3 2v2H7V4z"
RANDOM_PATH = (
    "M18 6.01L14 9V7h-4l-5 8H2v-2h2l5-8h5V3zM2 5h3l1.15 2.17l-1.12 1.8L4 7H2zm"
    "16 9.01L14 17v-2H9l-1.15-2.17l1.12-1.8L10 13h4v-2z"
)

# Load SF Pro Bold once, instanced to a specific weight/optical size.
_font = TTFont(SF_FONT)
_font = instantiateVariableFont(_font, {"wght": 700, "opsz": 48, "wdth": 100})
_glyph_set = _font.getGlyphSet()
_cmap = _font.getBestCmap()
UPEM = _font["head"].unitsPerEm


def text_paths(text):
    """Return (list of (advance_x, svg_path_d) pairs, total advance) in font units."""
    paths = []
    x = 0
    for ch in text:
        gname = _cmap.get(ord(ch))
        if gname is None:
            x += UPEM // 4
            continue
        g = _glyph_set[gname]
        pen = SVGPathPen(_glyph_set)
        g.draw(pen)
        d = pen.getCommands()
        if d:
            paths.append((x, d))
        x += g.width
    return paths, x


def wordmark_group(text, fs_px, baseline_x, baseline_y, fill=FG):
    """Render a flattened SF Pro Bold wordmark. Returns (svg_group, rendered_width_px)."""
    paths, total = text_paths(text)
    scale = fs_px / UPEM
    inner = "\n".join(
        f'      <path transform="translate({tx} 0)" d="{d}"/>' for tx, d in paths
    )
    return (
        f'  <g transform="translate({baseline_x} {baseline_y}) '
        f'scale({scale:.5f} -{scale:.5f})" fill="{fill}">\n{inner}\n  </g>',
        total * scale,
    )


def render_svg(svg_text, w, h, out_png):
    tmp = REPO / "_tmp_asset.svg"
    tmp.write_text(svg_text)
    subprocess.run(
        ["rsvg-convert", "-w", str(w), "-h", str(h), "-o", str(out_png), str(tmp)],
        check=True,
    )
    tmp.unlink()


# --- Plugin manifest icon + Marketplace app icon -----------------------------

# QUOTE_PATH visible glyph: x ∈ [5, 19] (width 14), y ∈ [7, 17] (height 10),
# in a 24×24 viewBox. Path-coord center is (12, 12).


def square_icon_svg(size):
    """Square name-focused icon: quotes mark above the 'Type Deck' wordmark."""
    fs = int(size * 56 / 288)
    # Sized so the visible glyph height ≈ 33% of the canvas (matches the
    # previous mark's visual weight).
    quote_scale = size * 0.033
    quote_cx = size / 2
    quote_cy = size * 85 / 288
    quote_x = quote_cx - 12 * quote_scale
    quote_y = quote_cy - 12 * quote_scale
    _, text_w = wordmark_group("Type Deck", fs, 0, 0)
    text_x = (size - text_w) / 2
    baseline = size * 200 / 288
    wm, _ = wordmark_group("Type Deck", fs, text_x, baseline)
    return f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {size} {size}">
  <rect width="{size}" height="{size}" fill="{BG}"/>
  <g transform="translate({quote_x} {quote_y}) scale({quote_scale})" fill="{FG}">
    <path d="{QUOTE_PATH}"/>
  </g>
{wm}
</svg>
"""


def category_icon_svg(size):
    """Sidebar category icon: white quotes glyph on transparent background."""
    # Fit the visible glyph (14 wide × 10 tall) into ~85% of the canvas.
    quote_scale = size * 0.85 / 14
    quote_x = size / 2 - 12 * quote_scale
    quote_y = size / 2 - 12 * quote_scale
    return f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {size} {size}">
  <g transform="translate({quote_x} {quote_y}) scale({quote_scale})" fill="{FG}">
    <path d="{QUOTE_PATH}"/>
  </g>
</svg>
"""


def build_icons():
    # Plugin manifest icon: 256 + 512 (per Elgato spec).
    render_svg(square_icon_svg(256), 256, 256, PLUGIN_IMGS / "marketplace.png")
    render_svg(square_icon_svg(512), 512, 512, PLUGIN_IMGS / "marketplace@2x.png")
    # Sidebar category icon: 28 + 56 (per Elgato spec).
    render_svg(category_icon_svg(28), 28, 28, PLUGIN_IMGS / "category-icon.png")
    render_svg(category_icon_svg(56), 56, 56, PLUGIN_IMGS / "category-icon@2x.png")
    # Marketplace App Icon: 288 (separate file, gitignored — uploaded directly).
    render_svg(square_icon_svg(288), 288, 288, DOCS / "marketplace-app-icon.png")


# --- Thumbnail ----------------------------------------------------------------


def build_thumbnail():
    w, h = 1920, 960
    fs = 200
    _, text_w = wordmark_group("Type Deck", fs, 0, 0)

    quote_scale = 10
    quote_size = 24 * quote_scale
    # Combined visual width: text + gap + visible quote width (14*scale).
    gap = 80
    visible_quote_w = 14 * quote_scale
    combined_w = text_w + gap + visible_quote_w
    text_x = (w - combined_w) / 2
    baseline = h / 2 - 10
    wm, _ = wordmark_group("Type Deck", fs, text_x, baseline)

    tag_fs = 56
    _, tag_w = wordmark_group("Human-feel typing for Stream Deck", tag_fs, 0, 0)
    tag_x = (w - tag_w) / 2
    tag_baseline = baseline + 130
    tag, _ = wordmark_group(
        "Human-feel typing for Stream Deck", tag_fs, tag_x, tag_baseline, fill=MUTED
    )

    # Place quote so its visible-left edge sits `gap` px right of the text.
    quote_x = text_x + text_w + gap - 5 * quote_scale
    quote_y = baseline - quote_size * 0.72

    svg = f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {w} {h}">
  <rect width="{w}" height="{h}" fill="{BG}"/>
  <g transform="translate({quote_x} {quote_y}) scale({quote_scale})" fill="{ACCENT}">
    <path d="{QUOTE_PATH}"/>
  </g>
{wm}
{tag}
</svg>
"""
    render_svg(svg, w, h, DOCS / "marketplace-thumbnail.png")


# --- Gallery 1: Three-actions overview ---------------------------------------


def build_gallery_actions():
    w, h = 1920, 960
    title_fs = 88
    sub_fs = 36

    head_paths, head_w = text_paths("Three actions")
    head_scale = title_fs / UPEM
    head_w_px = head_w * head_scale
    head_x = (w - head_w_px) / 2
    head_baseline = 200
    head_inner = "\n".join(
        f'      <path transform="translate({tx} 0)" d="{d}"/>'
        for tx, d in head_paths
    )

    actions = [
        ("Type text", "Snippet, signature, demo line", QUOTE_PATH, 24),
        ("Cycle next", "Each press types the next line", CYCLE_PATH, 16),
        ("Random pick", "Each press picks a random line", RANDOM_PATH, 20),
    ]

    col_w = w // 3
    icon_size = 200
    icon_y = h // 2 - 20

    parts = [
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {w} {h}">',
        f'  <rect width="{w}" height="{h}" fill="{BG}"/>',
        f'  <g transform="translate({head_x} {head_baseline}) '
        f'scale({head_scale:.5f} -{head_scale:.5f})" fill="{FG}">',
        head_inner,
        "  </g>",
    ]

    for i, (name, sub, path, vb) in enumerate(actions):
        cx = col_w * i + col_w / 2
        scale = icon_size / vb
        ix = cx - icon_size / 2
        parts.append(
            f'  <g transform="translate({ix} {icon_y}) scale({scale})" fill="{FG}">\n'
            f'    <path d="{path}"/>\n'
            f"  </g>"
        )
        np, nw = text_paths(name)
        ns = 56 / UPEM
        nx = cx - (nw * ns) / 2
        ny = icon_y + icon_size + 90
        ninner = "\n".join(
            f'      <path transform="translate({tx} 0)" d="{d}"/>' for tx, d in np
        )
        parts.append(
            f'  <g transform="translate({nx} {ny}) '
            f'scale({ns:.5f} -{ns:.5f})" fill="{FG}">\n{ninner}\n  </g>'
        )
        sp, sw = text_paths(sub)
        ss = sub_fs / UPEM
        sx = cx - (sw * ss) / 2
        sy = ny + 80
        sinner = "\n".join(
            f'      <path transform="translate({tx} 0)" d="{d}"/>' for tx, d in sp
        )
        parts.append(
            f'  <g transform="translate({sx} {sy}) '
            f'scale({ss:.5f} -{ss:.5f})" fill="{MUTED}">\n{sinner}\n  </g>'
        )

    parts.append("</svg>")
    render_svg("\n".join(parts), w, h, DOCS / "marketplace-gallery-1.png")


# --- Gallery 2 & 3: cropped screenshots --------------------------------------


def build_gallery_screenshots():
    src = DOCS / "screenshot.png"
    # Top portion: Stream Deck app with button grid + plugin browser.
    subprocess.run(
        [
            "magick",
            str(src),
            "-crop",
            "1924x1280+0+0",
            "+repage",
            "-resize",
            "x900",
            "-background",
            BG,
            "-gravity",
            "center",
            "-extent",
            "1920x960",
            str(DOCS / "marketplace-gallery-2.png"),
        ],
        check=True,
    )
    # Middle portion: property inspector settings panel.
    subprocess.run(
        [
            "magick",
            str(src),
            "-crop",
            "1924x1700+0+1200",
            "+repage",
            "-resize",
            "x900",
            "-background",
            BG,
            "-gravity",
            "center",
            "-extent",
            "1920x960",
            str(DOCS / "marketplace-gallery-3.png"),
        ],
        check=True,
    )


if __name__ == "__main__":
    build_icons()
    build_thumbnail()
    build_gallery_actions()
    build_gallery_screenshots()
    print("done")
